"""Jobs package for background task monitoring, scheduled jobs, and orchestration."""

from __future__ import annotations

from bot.jobs.base import (
    OrchestratedScheduler,
    ScheduledJob,
)
from bot.jobs.legacy import (
    _db_pruning_loop,
    _live_watch_loop,
    _peak_digest_loop,
    _resource_monitor_loop,
    _sheet_import_loop,
    _stats_prefetch_loop,
    _stats_session_refresh_loop,
    _tracking_monitor_loop,
    start_db_pruning,
    start_live_watch_monitor,
    start_peak_digest,
    start_resource_monitor,
    start_sheet_import_monitor,
    start_stats_prefetch,
    start_stats_session_refresh,
    start_tracking_monitor,
    stop_db_pruning,
    stop_live_watch_monitor,
    stop_peak_digest,
    stop_resource_monitor,
    stop_sheet_import_monitor,
    stop_stats_prefetch,
    stop_stats_session_refresh,
    stop_tracking_monitor,
)
from bot.jobs.tasks import (
    DbPruningJob,
    LiveWatchJob,
    PeakDigestJob,
    ResourceMonitorJob,
    SheetImportJob,
    StatsPrefetchJob,
    StatsSessionRefreshJob,
    TrackingMonitorJob,
    start_orchestrated_scheduler,
    stop_orchestrated_scheduler,
)

__all__ = [
    "ScheduledJob",
    "OrchestratedScheduler",
    "TrackingMonitorJob",
    "ResourceMonitorJob",
    "DbPruningJob",
    "StatsSessionRefreshJob",
    "StatsPrefetchJob",
    "LiveWatchJob",
    "SheetImportJob",
    "PeakDigestJob",
    "start_orchestrated_scheduler",
    "stop_orchestrated_scheduler",
    "start_live_watch_monitor",
    "stop_live_watch_monitor",
    "start_sheet_import_monitor",
    "stop_sheet_import_monitor",
    "start_tracking_monitor",
    "stop_tracking_monitor",
    "start_resource_monitor",
    "stop_resource_monitor",
    "start_stats_session_refresh",
    "stop_stats_session_refresh",
    "start_stats_prefetch",
    "stop_stats_prefetch",
    "start_peak_digest",
    "stop_peak_digest",
    "start_db_pruning",
    "stop_db_pruning",
    "_live_watch_loop",
    "_sheet_import_loop",
    "_stats_prefetch_loop",
    "_peak_digest_loop",
    "_stats_session_refresh_loop",
    "_tracking_monitor_loop",
    "_resource_monitor_loop",
    "_db_pruning_loop",
]
