"""Configuration helpers for environment-based application settings.

This module isolates everything related to reading runtime configuration from
environment variables. In this project, configuration currently comes from a
local `.env` file loaded through `python-dotenv`.

The rest of the codebase should not hardcode secrets such as the Telegram bot
token. Instead, startup code calls `load_settings()` and receives a typed
`Settings` object that can be passed to other modules.
"""

from dataclasses import dataclass
import os

from dotenv import load_dotenv

PATH_TO_ENV = os.path.join(os.path.dirname(__file__), "..", ".env")


@dataclass
class Settings:
    """Container for runtime settings used by the bot.

    Attributes:
        telegram_bot_token (str): Secret token generated by BotFather and used
            to authenticate the bot against Telegram's API.
        log_level (str): Desired logging verbosity for console output.
        football_data_provider (str): Provider identifier used to decide how
            fixtures and standings should be loaded.
        football_data_api_key (str | None): Optional API key reserved for a
            future real football-data integration.
        watchlist_days_ahead (int): Number of days inspected when building the
            weekly watchlist.
        watchlist_imbalance_threshold (float): Minimum imbalance score needed
            for a fixture to be saved in the watchlist.

    Notes:
        Wrapping configuration in a dataclass makes startup code clearer and
        avoids passing loose strings around the project.
    """

    telegram_bot_token: str
    log_level: str = "INFO"
    football_data_provider: str = "mock"
    football_data_api_key: str | None = None
    watchlist_days_ahead: int = 7
    watchlist_imbalance_threshold: float = 60.0


def load_settings() -> Settings:
    """Load runtime settings from the local `.env` file.

    This function is called during startup from `main.py`. It loads
    environment variables from disk, validates that required values are
    present, and returns a `Settings` instance for the rest of the system.

    Returns:
        Settings: Parsed and validated configuration for the current run.

    Side Effects:
        Loads environment variables into the current Python process using
        `python-dotenv`.

    Raises:
        FileNotFoundError: If the `.env` file cannot be found or loaded from
            the expected project path.
        ValueError: If required or numeric configuration values are invalid.

    Notes:
        Secrets are loaded from environment variables instead of being
        hardcoded in source files. This is safer for local development and for
        future deployments.
    """

    # The project uses an explicit path so configuration is loaded from the
    # repository root even when the program is started from another directory.
    if not load_dotenv(PATH_TO_ENV):
        raise FileNotFoundError(
            f"No se pudo cargar el archivo .env desde la ruta: {PATH_TO_ENV}"
        )

    # Values are normalized immediately so the rest of the application can use
    # them without worrying about extra spaces or mixed-case log levels.
    telegram_bot_token = os.getenv("TELEGRAM_BOT_TOKEN", "").strip()
    log_level = os.getenv("LOG_LEVEL", "INFO").strip().upper() or "INFO"
    football_data_provider = os.getenv("FOOTBALL_DATA_PROVIDER", "mock").strip().lower() or "mock"
    football_data_api_key = os.getenv("FOOTBALL_DATA_API_KEY", "").strip() or None
    watchlist_days_ahead = _parse_positive_int(
        os.getenv("WATCHLIST_DAYS_AHEAD", "7"),
        variable_name="WATCHLIST_DAYS_AHEAD",
    )
    watchlist_imbalance_threshold = _parse_threshold(
        os.getenv("WATCHLIST_IMBALANCE_THRESHOLD", "60"),
    )

    if not telegram_bot_token:
        raise ValueError(
            "Falta la variable TELEGRAM_BOT_TOKEN. Creá el archivo .env a partir de .env.example."
        )

    return Settings(
        telegram_bot_token=telegram_bot_token,
        log_level=log_level,
        football_data_provider=football_data_provider,
        football_data_api_key=football_data_api_key,
        watchlist_days_ahead=watchlist_days_ahead,
        watchlist_imbalance_threshold=watchlist_imbalance_threshold,
    )


def _parse_positive_int(raw_value: str, variable_name: str) -> int:
    """Parse a positive integer environment variable.

    Args:
        raw_value (str): Raw environment value read as text.
        variable_name (str): Variable name used for error reporting.

    Returns:
        int: Parsed positive integer value.

    Raises:
        ValueError: If the value cannot be parsed or is not positive.
    """

    try:
        parsed_value = int(raw_value.strip())
    except ValueError as error:
        raise ValueError(f"{variable_name} debe ser un número entero positivo.") from error

    if parsed_value <= 0:
        raise ValueError(f"{variable_name} debe ser mayor que cero.")

    return parsed_value


def _parse_threshold(raw_value: str) -> float:
    """Parse and validate the minimum watchlist imbalance threshold.

    Args:
        raw_value (str): Raw environment value read as text.

    Returns:
        float: Threshold value constrained to the 0-100 range.

    Raises:
        ValueError: If the value is not numeric or falls outside the accepted
            range.
    """

    try:
        parsed_value = float(raw_value.strip())
    except ValueError as error:
        raise ValueError("WATCHLIST_IMBALANCE_THRESHOLD debe ser un número.") from error

    if parsed_value < 0 or parsed_value > 100:
        raise ValueError("WATCHLIST_IMBALANCE_THRESHOLD debe estar entre 0 y 100.")

    return parsed_value
